import Navbar from "@/components/Navbar";
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
          <Navbar />
          {children}
          {/* Footer */}
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
